name = "ParticleTrackingSim"
uuid = "2f0095eb-734c-4489-8f34-7b126f77cb62"
authors = ["dainakai <dai.nakai@proton.me>"]
version = "0.1.0"

[deps]
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
TOML = "1.0.3"
julia = "1"
